/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package smartwastebin_interfaz;

import java.util.List;
import javax.swing.JTextArea;
import javax.swing.JScrollPane;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import java.awt.Dimension;
import java.awt.Font;
import java.util.LinkedHashSet;
import java.util.Set;
import java.util.ArrayList;

/**
 *
 * @author Diego Mejia
 */
public class LobbyProductos extends javax.swing.JFrame {

    
    /**
     * Creates new form LobbyProductos
     */
    public LobbyProductos() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btn_Limpieza = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btn_proceso = new javax.swing.JButton();
        elpepe1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn_registrarproducto = new javax.swing.JButton();
        btn_VerProductos = new javax.swing.JButton();
        btn_ElimProducto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(108, 99, 255));
        jPanel2.setForeground(new java.awt.Color(102, 102, 102));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("LIMPIEZA");

        btn_Limpieza.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Limpieza.setText("APLICAR LIMPIEZA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(btn_Limpieza, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addGap(46, 46, 46)
                .addComponent(btn_Limpieza, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(108, 99, 255));
        jPanel3.setForeground(new java.awt.Color(102, 102, 102));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PROCESOS");

        btn_proceso.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_proceso.setText("APLICAR PROCESO");
        btn_proceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_procesoActionPerformed(evt);
            }
        });

        elpepe1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        elpepe1.setText("come back");
        elpepe1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elpepe1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel2)
                .addContainerGap(92, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_proceso, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(elpepe1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addGap(32, 32, 32)
                .addComponent(btn_proceso, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(elpepe1)
                .addGap(20, 20, 20))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("LOBBY");

        btn_registrarproducto.setBackground(new java.awt.Color(108, 99, 255));
        btn_registrarproducto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_registrarproducto.setForeground(new java.awt.Color(255, 255, 255));
        btn_registrarproducto.setText("REGISTRAR PRODUCTOS");
        btn_registrarproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrarproductoActionPerformed(evt);
            }
        });

        btn_VerProductos.setBackground(new java.awt.Color(108, 99, 255));
        btn_VerProductos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_VerProductos.setForeground(new java.awt.Color(255, 255, 255));
        btn_VerProductos.setText("VER PRODUCTOS");
        btn_VerProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_VerProductosActionPerformed(evt);
            }
        });

        btn_ElimProducto.setBackground(new java.awt.Color(108, 99, 255));
        btn_ElimProducto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_ElimProducto.setForeground(new java.awt.Color(255, 255, 255));
        btn_ElimProducto.setText("ELIMINAR PRODUCTOS");
        btn_ElimProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ElimProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(29, 29, 29))
                            .addComponent(btn_registrarproducto, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_ElimProducto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(btn_VerProductos)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 85, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(btn_registrarproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(btn_VerProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(btn_ElimProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_procesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_procesoActionPerformed
        new AplicarProceso().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_procesoActionPerformed

    private void btn_registrarproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrarproductoActionPerformed
        Formulario Formulario = new Formulario();
        Formulario.setVisible(true);
        this.dispose();      // TODO add your handling code here:
    }//GEN-LAST:event_btn_registrarproductoActionPerformed

    private void btn_ElimProductoActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
            // Mostrar diálogo para ingresar nombre del producto
            String nombreProducto = JOptionPane.showInputDialog(this, "Ingrese el nombre del producto a eliminar:", "Eliminar Producto", JOptionPane.QUESTION_MESSAGE);
            
            if (nombreProducto != null && !nombreProducto.trim().isEmpty()) {
                // Confirmar eliminación
                int confirmacion = JOptionPane.showConfirmDialog(this, 
                    "¿Está seguro que desea eliminar el producto " + nombreProducto + "?", 
                    "Confirmar Eliminación", 
                    JOptionPane.YES_NO_OPTION);
                
                if (confirmacion == JOptionPane.YES_OPTION) {
                    eliminarProducto(nombreProducto.trim());
                }
            } else {
                JOptionPane.showMessageDialog(this, "Debe ingresar un nombre válido", "Error", JOptionPane.WARNING_MESSAGE);
            }
        }


    private void btn_VerProductosActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            // Leer archivos
            List<String> users = Files.readAllLines(Paths.get("users.csv"));
            List<String> products = Files.readAllLines(Paths.get("products.csv"));
            
            // Crear StringBuilder con formato organizado
            StringBuilder sb = new StringBuilder();
            sb.append("=== USUARIOS ===\n");
            for (String line : users) {
                String[] parts = line.split(",");
                if(parts.length >= 3) {
                    // Muestra ID en campo ID y Nombre en campo Nombre
                    sb.append(String.format("ID: %-10s Nombre: %s\n", parts[0], parts[1]));
                }
            }
            
            // Modifica el bloque de productos para eliminar duplicados
            Set<String> productosUnicos = new LinkedHashSet<>(products);
            sb.append("\n=== PRODUCTOS ===\n");
            for (String line : productosUnicos) {
                String[] parts = line.split(",");
                if(parts.length >= 3) {
                    sb.append(String.format("ID: %-10s Nombre: %-20s Tipo: %s\n", 
                        parts[0], parts[1], parts[2]));
                }
            }
            
            // Crear área de texto con scroll
            JTextArea textArea = new JTextArea(sb.toString());
            textArea.setEditable(false);
            textArea.setFont(new Font("Monospaced", Font.PLAIN, 12));
            JScrollPane scrollPane = new JScrollPane(textArea);
            scrollPane.setPreferredSize(new Dimension(600, 500));
            
            // Mostrar ventana emergente
            JOptionPane.showMessageDialog(this, scrollPane, "Datos Registrados", JOptionPane.PLAIN_MESSAGE);
            
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error al leer los archivos", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }                                                

    private void elpepe1ActionPerformed(java.awt.event.ActionEvent evt) {
        Lobby lobby = new Lobby();
        lobby.setVisible(true);
        this.dispose();
    }

    private void eliminarProducto(String nombreProducto) {
        try {
            // Leer archivo products.csv
            List<String> lineas = Files.readAllLines(Paths.get("products.csv"));
            
            // Filtrar líneas que no contengan el producto a eliminar
            List<String> nuevasLineas = new ArrayList<>();
            for (String linea : lineas) {
                String[] partes = linea.split(",");
                if (partes.length >= 2 && !partes[1].equalsIgnoreCase(nombreProducto)) {
                    nuevasLineas.add(linea);
                }
            }
            
            // Escribir archivo actualizado
            Files.write(Paths.get("products.csv"), nuevasLineas);
            
            JOptionPane.showMessageDialog(this, "Producto eliminado exitosamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error al eliminar el producto", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }




    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LobbyProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LobbyProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LobbyProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LobbyProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LobbyProductos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ElimProducto;
    private javax.swing.JButton btn_Limpieza;
    private javax.swing.JButton btn_VerProductos;
    private javax.swing.JButton btn_proceso;
    private javax.swing.JButton btn_registrarproducto;
    private javax.swing.JButton elpepe1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}


