/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package smartwastebin_interfaz;

import smartwastebin_interfaz.model.UserManager;
import smartwastebin_interfaz.model.User;
import javax.swing.*;
/*
 *
 * @author JAVIER Y KLEVER
 */
public class Login extends javax.swing.JFrame {
    UserManager userManager = new UserManager();
    
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        //Aqui puedes predeterminar el tamaño de una ventana
        // Establecer el tamaño predeterminado
        this.setSize(518, 410);
        // Evitar que el usuario cambie el tamaño
        this.setResizable(false);
        //posicionar siempre en el medio
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        phraseLabel = new javax.swing.JLabel();
        btn_comeBack = new javax.swing.JButton();
        rightPanel = new javax.swing.JPanel();
        rightTitleLabel = new javax.swing.JLabel();
        welcomeLabel = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        text_nameLogin = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        text_passLogin = new javax.swing.JPasswordField();
        btn_login = new javax.swing.JButton();
        noAccountLabel = new javax.swing.JLabel();
        btn_singup = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 400));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        leftPanel.setBackground(new java.awt.Color(255, 255, 255));
        leftPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        titleLabel.setText("Smart");
        leftPanel.add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        phraseLabel.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        phraseLabel.setText("Be part of the solution, not the pollution.");
        leftPanel.add(phraseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        btn_comeBack.setBackground(new java.awt.Color(108, 99, 255));
        btn_comeBack.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_comeBack.setForeground(new java.awt.Color(255, 255, 255));
        btn_comeBack.setText("Come Back");
        btn_comeBack.setBorderPainted(false);
        btn_comeBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_comeBack.setFocusPainted(false);
        btn_comeBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_comeBackActionPerformed(evt);
            }
        });
        leftPanel.add(btn_comeBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 100, 35));

        getContentPane().add(leftPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 400));

        rightPanel.setBackground(new java.awt.Color(108, 99, 255));
        rightPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rightTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        rightTitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        rightTitleLabel.setText("Waste Bin");
        rightPanel.add(rightTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        welcomeLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        welcomeLabel.setForeground(new java.awt.Color(255, 255, 255));
        welcomeLabel.setText("¡Welcome!");
        rightPanel.add(welcomeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, -1, -1));

        idLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        idLabel.setForeground(new java.awt.Color(255, 255, 255));
        idLabel.setText("ID");
        rightPanel.add(idLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        text_nameLogin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        text_nameLogin.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        text_nameLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_nameLoginActionPerformed(evt);
            }
        });
        rightPanel.add(text_nameLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 250, 35));

        passwordLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(255, 255, 255));
        passwordLabel.setText("Password");
        rightPanel.add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        text_passLogin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        text_passLogin.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        rightPanel.add(text_passLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 250, 35));

        btn_login.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_login.setText("Log in");
        btn_login.setBorderPainted(false);
        btn_login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_login.setFocusPainted(false);
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        rightPanel.add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 250, 35));

        noAccountLabel.setForeground(new java.awt.Color(255, 255, 255));
        noAccountLabel.setText("I have no account");
        rightPanel.add(noAccountLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, -1, -1));

        btn_singup.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_singup.setForeground(new java.awt.Color(255, 255, 255));
        btn_singup.setText("Sign up");
        btn_singup.setBorder(null);
        btn_singup.setBorderPainted(false);
        btn_singup.setContentAreaFilled(false);
        btn_singup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_singup.setFocusPainted(false);
        btn_singup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_singupActionPerformed(evt);
            }
        });
        rightPanel.add(btn_singup, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, -1, -1));

        getContentPane().add(rightPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 350, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void text_nameLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_nameLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_nameLoginActionPerformed

    private void text_passLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_passLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_passLoginActionPerformed

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        String idUser = text_nameLogin.getText();
        String pass = text_passLogin.getText();

        // Usa la instancia userManager para llamar a login
        User user = userManager.login(idUser, pass);
        
        if (user != null) {
            JOptionPane.showMessageDialog(this, "Welcome " + user.getName());
            new LobbyProductos().setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "ID de usuario o contraseña incorrectos.");
        }
    }//GEN-LAST:event_btn_loginActionPerformed

    private void btn_singupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_singupActionPerformed
        new Register().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_singupActionPerformed

    private void btn_comeBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_comeBackActionPerformed
        new Lobby().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_comeBackActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_comeBack;
    private javax.swing.JButton btn_login;
    private javax.swing.JButton btn_singup;
    private javax.swing.JLabel idLabel;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JLabel noAccountLabel;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel phraseLabel;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JLabel rightTitleLabel;
    private javax.swing.JTextField text_nameLogin;
    private javax.swing.JPasswordField text_passLogin;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
